Add reader for EMPAD raw files
py4dstem/py4DSTEM pull request #177
Opened 2021-06-29 00:45 UTC by sezelt

This PR adds the ability to read files from the original EMPAD (support for EMPAD 2 is unknown, as I don't have any test files for that). The reader supports reading into memory, memory-mapping, and bin-on-read to RAM. 

Metadata is not supported as there is no meaningful metadata that I am aware of in the file format. (A separate XML file is used for that metadata, but I have not added support for reading from that file. Perhaps this would be handled through a `kwarg` like `metadata_file` if we chose to implement it, since in the examples I've seen the XML does not have the same filename as the data)

2021-07-21 19:41 UTC, bsavitzky requested changes
Looks good.  The only meaningful edit requested is to please confirm that this function does *not* include the 2 metadata lines in the output datacube, and to edit the docstring accordingly

2021-07-21 19:41 UTC, bsavitzky commented on py4DSTEM/io/nonnative/empad.py
> +from pdb import set_trace
We can remove this, no?

2021-07-21 19:41 UTC, bsavitzky commented on py4DSTEM/io/nonnative/empad.py
> +    # fmt: off
rm? This is leftover from using Black for formatting?

2021-07-21 19:41 UTC, bsavitzky commented on py4DSTEM/io/nonnative/empad.py
> +    # fmt: on
rm?

2021-07-21 19:41 UTC, bsavitzky commented on py4DSTEM/io/nonnative/empad.py
> +
rm blank line

2021-07-21 19:41 UTC, bsavitzky commented on py4DSTEM/io/nonnative/empad.py
> +                    raw data only can be accessed data[:,:,:128,:]
It says here that the fn returns the datacube *with* the 2 metadata lines, but the code (lines 64,68,72) do *not* appear to be including the metadata lines in the returned datacube.  I think this is probably the right way to do this, but we should then change the `Note` and `Returns` descriptions in this docstring

2021-07-22 00:13 UTC, sezelt commented
@bsavitzky I agree with all your comments, and addressed them in this new commit. I edited the docstring to clarify that we do indeed return only the 128x128 valid data region, and also corrected that we are returning the `DataCube`, not a `np.ndarray`. Those other little comment lines were indeed there to prevent black from reformatting those assert statements to look insane, but since we in general aren't (yet!) running a formatter on the whole codebase I just nixed them.

2021-07-22 03:10 UTC, bsavitzky commented
> @bsavitzky I agree with all your comments, and addressed them in this new commit. I edited the docstring to clarify that we do indeed return only the 128x128 valid data region, and also corrected that we are returning the `DataCube`, not a `np.ndarray`. Those other little comment lines were indeed there to prevent black from reformatting those assert statements to look insane, but since we in general aren't (yet!) running a formatter on the whole codebase I just nixed them.

Thanks @sezelt - one last thing - I take it you don't still need to be importing the python debugger, yes?  Cool to remove this line?

2021-07-22 18:01 UTC, sezelt commented
Yes, it's safe to remove `pdb`.

2021-07-22 19:34 UTC, bsavitzky approved these changes

2021-07-22 19:34 UTC, merged