add dtype selection and progess bar to bin_data_mmap
py4dstem/py4DSTEM pull request #180
Opened 2021-07-01 22:31 UTC by sezelt

A tiny tweak to allow choice of the target dtype when binning a memory mapped DataCube. Changes the for loop to use `tqdmnd` for progress updates.

2021-07-16 20:17 UTC, sezelt commented
I have added another tiny tweak, which is to use for loops in the virtual image functions, as a user encountered problems with running out of memory generating an annular image, even when using a memory-mapped dataset.

2021-07-21 16:42 UTC, bsavitzky requested changes

2021-07-21 16:42 UTC, bsavitzky commented on py4DSTEM/io/datastructure/datacube.py
>          self = preprocess.bin_data_mmap(self, bin_factor)
shouldn't line 100 have `dtype=dtype`?

2021-07-21 17:55 UTC, bsavitzky approved these changes

2021-07-21 17:55 UTC, merged