07-08 acom notebook
py4dstem/py4DSTEM pull request #303
Opened 2022-07-15 22:56 UTC by alex-rakowski

Changes required to run 07-08 notebooks.

2022-07-15 23:59 UTC, sezelt commented
I don't understand these changes at all. You've added 8 new files that are (modified?) copies of old ones but with "2" added to the name, so the diffs are meaningless, and they aren't even imported anywhere.

2022-07-16 09:29 UTC, alex-rakowski commented
Not sure why `* 2.py` were created but I've removed them now, but the PR looks correct now.

2022-07-16 19:49 UTC, sezelt requested changes
I think the only necessary change is the `..io.datastructure.py4dstem.DataCube` import thing.

PR #304 fully corrects some of the `preprocess` bugs that this hacks, which will cause merge conflicts. So I think we should merge #304 first and then resolve the conflicts on this one.

2022-07-16 19:49 UTC, sezelt commented on py4DSTEM/preprocess/__init__.py
> +# from .electroncount import * # get_maximal_points not in utils anymore will break
This broken import is fixed in #304

2022-07-16 19:49 UTC, sezelt commented on py4DSTEM/preprocess/relativity.py
> +from ..io.datastructure.py4dstem import DataCube
I think you should always import `py4DSTEM.io.DataCube`. We've had problems before where multiple instances of the class, with different `id`, get created due to importing through different paths. When this happens, `assert isinstance(datacube, py4DSTEM.io.DataCube` can fail

2022-07-16 19:49 UTC, sezelt commented on py4DSTEM/preprocess/electroncount.py
> +# get_maximal_points has gone missing / renamed will break
This broken import is fixed by #304

2022-07-18 16:40 UTC, bsavitzky reviewed
This looks good to me!!  Following Steve's comment, I'll wait until we can discuss and finish PR #304, and then can come back and finish pulling this code in

2022-07-18 20:29 UTC, bsavitzky approved these changes

2022-07-18 20:49 UTC, merged