Introduce featurization - generic clustering class for any numpy array
py4dstem/py4DSTEM pull request #350
Opened 2022-09-26 17:48 UTC by abruefach

This class is built to take in any numpy array and perform clustering on it.  A general workflow includes the following (demonstrated using the code and files attached in Featurization_Demo.zip):

1. Instantiating the class with the input features and keys (names) of the features (right now referred to as keys, since they are stored in a dictionary)
2. Prepare on the input features. Features can be concatenated, averaged, scaled, deleted, etc.
3. Call an unsupervised learning method on the features - this currently requires the user to input which features they would like to call the unsupervised learning model on, as well as other input parameters. The method that is best tested is the NMF_iterative. This can be called i number of times (controlled by the iters argument, runs different random seeds) - the output clusters of these models can then be combined to create an ensemble model later on, i.e. 'consensus clustering'
4. Call 'get_class_ims' - this just restructures the results from the unsupervised learning model into real space images.
5. Perform post processing on clusters if required - the demo code I'll send over includes a spatial_separation method, which separates spatially distinct regions based on their x,y coordinates and weighs in the feature maps.
6. Perform consensus clustering - this method performs both label correspondence and consensus clustering, which matches clusters based on similarity and then averages the classes. I may want to split the label correspondence and consensus clustering up in the future, it may make more sense logically for these to be separate.

I'd love suggestions on how to make this module more user friendly/generally better, it is functional right now but not optimal :)

[Featurization_Demo.zip](https://github.com/py4dstem/py4DSTEM/files/9648426/Featurization_Demo.zip)

2022-11-08 20:39 UTC, bsavitzky requested changes
Great start.  Thanks Alex!

2022-11-08 20:39 UTC, bsavitzky commented on py4DSTEM/process/classification/featurization.py
> +    def NMF_iterative(self, keys, max_components, merge_thresh, iters, random_state = None, return_all = True):
i'd suggest merging this function and the other `NMF` function into a single function.  If we set the `merge_thresh` default to some number greater than one, it should by default reduce to the normal `NMF` function

2022-11-08 20:39 UTC, bsavitzky commented on py4DSTEM/process/classification/featurization.py
> +    def get_class_DPs(self, keys, classification_method, thresh, dc):
maybe put `dc` at the beginning of the args and name it `datacube`

2022-11-08 20:39 UTC, bsavitzky commented on py4DSTEM/process/classification/featurization.py
> +                                          / (np.max(class_pattern) - np.min(class_pattern)))
i'd suggest changing the normalization to divide by the sum of the weights `W[...]`

2022-11-08 20:39 UTC, bsavitzky commented on py4DSTEM/process/classification/featurization.py
> +        classification_method (str): either 'nmf' or 'gmm' - finds location of clusters
can we have it work for other methods?

2022-11-08 20:39 UTC, bsavitzky commented on py4DSTEM/process/classification/featurization.py
> +                        t = threshold_otsu(image)
add a catch for a bad input

2022-12-13 14:41 UTC, abruefach commented on py4DSTEM/process/classification/featurization.py
> +        return
Vestigial method, removed in new version

2022-12-13 14:42 UTC, abruefach commented on py4DSTEM/process/classification/featurization.py
> +        return
This is modified in the new version to combine Featurization instances

2023-01-23 19:33 UTC, bsavitzky approved these changes

2023-01-23 19:33 UTC, merged