ptycho 0.14: weeding out bugs and bundling new features
py4dstem/py4DSTEM pull request #426
Opened 2023-05-09 20:46 UTC by smribet

This PR has new functionality for `phase` including: 
- compatibility with py4DSTEM `0.14`
- the option for real potentials 
- plotting updates including complex probes 
- standardization of regularization options across classes
- regularization along z direction for multislice
- overlap tomography for magnetic potentials 
- read/write functionality 

Updated tutorials [here](https://github.com/py4dstem/py4DSTEM_tutorials/tree/main/notebooks/version_0.14)

2023-05-17 21:23 UTC, sezelt requested changes
Excellent work, team. 
I have essentially two categories of comment:
1. In many places you redundantly use `kwargs.get(key,default)` followed by `kwargs.pop(key,None)`, which can be accomplished by one call to `kwargs.pop(key,default)`.
2. Some very severe regularizations are turned on by default now: `'potential'` mode on the object and `symmetrize_probe`. Do you have examples of experimental data where these make a substantial improvement?  These will undoubtedly help for simulated data with no inelastic scattering and no aberrations beyond C1, but my suspicion is that for experimental data these are too aggressive and should default to off.

2023-05-17 21:23 UTC, sezelt commented on py4DSTEM/process/phase/iterative_multislice_ptychography.py
> +        kwargs.pop("hue_start", None)
Same comment about combining get and pop

2023-05-17 21:23 UTC, sezelt commented on py4DSTEM/process/phase/iterative_simultaneous_ptychography.py
> +            kwargs.pop("invert", None)
Merge

2023-05-17 21:23 UTC, sezelt commented on py4DSTEM/process/phase/iterative_simultaneous_ptychography.py
> +
Merge

2023-05-17 21:23 UTC, sezelt commented on py4DSTEM/process/phase/iterative_overlap_magnetic_tomography.py
> +
Merge

2023-05-17 21:23 UTC, sezelt commented on py4DSTEM/process/phase/iterative_overlap_magnetic_tomography.py
> +        kwargs.pop("vmax_m", None)
Same

2023-05-17 21:23 UTC, sezelt commented on py4DSTEM/process/phase/iterative_overlap_tomography.py
> +            kwargs.pop("invert", None)
you know

2023-05-17 21:23 UTC, sezelt commented on py4DSTEM/process/phase/iterative_overlap_tomography.py
> +        kwargs.pop("hue_start", None)
😇

2023-05-17 21:31 UTC, sezelt commented
I have been informed that `symmetrize_probe` is indeed off by default. It is turned __off__ after zero iterations, not on.

2023-05-18 18:49 UTC, smribet commented on py4DSTEM/process/phase/iterative_base_class.py
> +                    self._rotation_curl_transpose = rotation_curl_transpose
I wanted to save these variables for making figures

2023-05-18 19:20 UTC, smribet commented on py4DSTEM/process/phase/iterative_dpc.py
> +            Cut-off frequency in A^-1 for high-pass butterworth filter
The datacube has to have real space calibrations!

2023-05-18 20:50 UTC, smribet commented on py4DSTEM/process/phase/utils.py
> +
updated!

2023-05-18 21:38 UTC, sezelt approved these changes

2023-05-18 21:48 UTC, smribet commented
Thank you for the helpful feedback!

2023-05-20 23:09 UTC, merged